[config]
version_check = false

[config.wallpaper]
set = true
command = "swww"
arguments = ["img", "--transition-type", "any", "--transition-step", "255", "--transition-fps", "60"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/matugen.conf'
post_hook = 'hyprctl reload'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.conf'
output_path = '~/.cache/wallpaper'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = 'kitten themes --reload-in=all matugen'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/matugen.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors/matugen.css'
post_hook = 'swaync-client -rs'

[templates.swayosd]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swayosd/colors/matugen.css'
post_hook = 'pkill swayosd-server;setsid -f swayosd-server >/dev/null 2>&1'
